version: "3.0"

services:
  mysql:
    ports:
      - 33306:3306
    image: mysql

  hazelcast:
    ports:
      - 5701:5701
    image: hazelcast/hazelcast
    volumes:
      - ./config/hazelcast/hazelcast.yaml:/opt/hazelcast/hazelcast.yaml

  hazelcast-manager:
    ports:
      - 38080:8080
    image: hazelcast/management-center:latest
